export const FETCHING_OBJECT_REQUESTED = 'FETCHING_OBJECT_REQUESTED'
export const FETCHING_OBJECT_SUCCESS = 'FETCHING_OBJECT_SUCCESS'
export const FETCHING_OBJECT_FAILURE = 'FETCHING_OBJECT_FAILURE'

export const CREATION_OBJECT_FAILURE = 'CREATION_OBJECT_FAILURE'
export const CREATION_OBJECT_REQUESTED = 'CREATION_OBJECT_REQUESTED'
export const CREATION_OBJECT_SUCCESS = 'CREATION_OBJECT_SUCCESS'

export const UPDATE_OBJECT_FAILURE = 'UPDATE_OBJECT_FAILURE'
export const UPDATE_OBJECT_REQUESTED = 'UPDATE_OBJECT_REQUESTED'
export const UPDATE_OBJECT_SUCCESS = 'UPDATE_OBJECT_SUCCESS'

export const FETCHING_ADDRESS_REQUESTED = 'FETCHING_ADDRESS_REQUESTED'
export const FETCHING_ADDRESS_SUCCESS = 'FETCHING_ADDRESS_SUCCESS'
export const FETCHING_ADDRESS_FAILURE = 'FETCHING_ADDRESS_FAILURE'

export const DELETE_OBJECT_FAILURE = 'DELETE_OBJECT_FAILURE'
export const DELETE_OBJECT_REQUESTED = 'DELETE_OBJECT_REQUESTED'
export const DELETE_OBJECT_SUCCESS = 'DELETE_OBJECT_SUCCESS'

export const DOWNLOAD_CONFIG_FAILURE = 'DELETE_OBJECT_FAILURE'
export const DOWNLOAD_CONFIG_REQUESTED = 'DELETE_OBJECT_REQUESTED'
export const DOWNLOAD_CONFIG_SUCCESS = 'DELETE_OBJECT_SUCCESS'

export const GET_THING_TOKEN = 'GET_THING_TOKEN'
export const GET_GATEWAY_TOKEN = 'GET_GATEWAY_TOKEN'
