export const FETCHING_POLICIES_REQUESTED = 'FETCHING_POLICIES_REQUESTED'
export const FETCHING_POLICIES_SUCCESS = 'FETCHING_POLICIES_SUCCESS'
export const FETCHING_POLICIES_FAILURE = 'FETCHING_POLICIES_FAILURE'

export const CREATION_POLICY_FAILURE = 'CREATION_POLICY_FAILURE'
export const CREATION_POLICY_REQUESTED = 'CREATION_POLICY_REQUESTED'
export const CREATION_POLICY_SUCCESS = 'CREATION_POLICY_SUCCESS'

export const UPDATE_POLICY_FAILURE = 'UPDATE_POLICY_FAILURE'
export const UPDATE_POLICY_REQUESTED = 'UPDATE_POLICY_REQUESTED'
export const UPDATE_POLICY_SUCCESS = 'UPDATE_POLICY_SUCCESS'

export const DELETE_POLICY_FAILURE = 'DELETE_POLICY_FAILURE'
export const DELETE_POLICY_REQUESTED = 'DELETE_POLICY_REQUESTED'
export const DELETE_POLICY_SUCCESS = 'DELETE_POLICY_SUCCESS'

export const REORDER_POLICY_FAILURE = 'REORDER_POLICY_FAILURE'
export const REORDER_POLICY_REQUESTED = 'REORDER_POLICY_REQUESTED'
export const REORDER_POLICY_SUCCESS = 'REORDER_POLICY_SUCCESS'
