export const FETCHING_REPORTS_REQUESTED = 'FETCHING_REPORTS_REQUESTED'
export const FETCHING_REPORTS_SUCCESS = 'FETCHING_REPORTS_SUCCESS'
export const FETCHING_REPORTS_FAILURE = 'FETCHING_REPORTS_FAILURE'
