export const FETCHING_ECOSYSTEMS_REQUESTED = 'FETCHING_ECOSYSTEMS_REQUESTED'
export const FETCHING_ECOSYSTEMS_SUCCESS = 'FETCHING_ECOSYSTEMS_SUCCESS'
export const FETCHING_ECOSYSTEMS_FAILURE = 'FETCHING_ECOSYSTEMS_FAILURE'

export const CREATE_ECOSYSTEM_REQUESTED = 'CREATE_ECOSYSTEM_REQUESTED'
export const CREATE_ECOSYSTEM_SUCCESS = 'CREATE_ECOSYSTEM_SUCCESS'
export const CREATE_ECOSYSTEM_FAILURE = 'CREATE_ECOSYSTEM_FAILURE'

export const REMOVE_ECOSYSTEM_REQUESTED = 'REMOVE_ECOSYSTEM_REQUESTED'
export const REMOVE_ECOSYSTEM_SUCCESS = 'REMOVE_ECOSYSTEM_SUCCESS'
export const REMOVE_ECOSYSTEM_FAILURE = 'REMOVE_ECOSYSTEM_FAILURE'

export const SET_CURRENT_ECOSYSTEM = 'SET_CURRENT_ECOSYSTEM'

export const APPEND_NEW_SERVICE = 'APPEND_NEW_SERVICE'

export const LOAD_ECOSYSTEM_REQUESTED = 'LOAD_ECOSYSTEM_REQUESTED'
export const REFRESH_ECOSYSTEM_REQUESTED = 'REFRESH_ECOSYSTEM_REQUESTED'
export const LOAD_ECOSYSTEM_SUCCESS = 'LOAD_ECOSYSTEM_SUCCESS'
export const REFRESH_ECOSYSTEM_SUCCESS = 'REFRESH_ECOSYSTEM_SUCCESS'

export const CREATE_ECOSYSTEM_GROUP_REQUESTED =
	'CREATE_ECOSYSTEM_GROUP_REQUESTED'
export const CREATE_ECOSYSTEM_GROUP_SUCCESS = 'CREATE_ECOSYSTEM_GROUP_SUCCESS'
export const CREATE_ECOSYSTEM_GROUP_FAILURE = 'CREATE_ECOSYSTEM_GROUP_FAILURE'

export const CREATE_SERVICE_REQUESTED = 'CREATE_SERVICE_REQUESTED'
export const CREATE_SERVICE_SUCCESS = 'CREATE_SERVICE_SUCCESS'
export const CREATE_SERVICE_FAILURE = 'CREATE_SERVICE_FAILURE'

export const FETCHING_NSP_REQUESTED = 'FETCHING_NSP_REQUESTED'
export const FETCHING_NSP_SUCCESS = 'FETCHING_NSP_SUCCESS'
export const FETCHING_NSP_FAILURE = 'FETCHING_NSP_FAILURE'
